=== hanneslehmann/as-db/src/main/resources/db.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="database" type="database" />

  <xsd:complexType name="database">
    <xsd:sequence>
      <xsd:element name="table" type="table" minOccurs="0"
        maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="table">
    <xsd:sequence>
      <xsd:element name="selectSQL" type="xsd:string"
        minOccurs="0" />
      <xsd:element name="countSQL" type="xsd:string"
        minOccurs="0" />
      <xsd:element name="insertSQL" type="xsd:string"
        minOccurs="0" />
      <xsd:element name="column" type="column" minOccurs="0"
        maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="catalog" type="xsd:string" />
    <xsd:attribute name="schema" type="xsd:string" />
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="type" type="tableType" />
    <xsd:attribute name="space" type="xsd:string" />
    <xsd:attribute name="fetchSize" type="xsd:int" />
  </xsd:complexType>

  <xsd:complexType name="column">
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="keySequence" type="xsd:short" />
    <xsd:attribute name="type" type="dataType" />
    <xsd:attribute name="size" type="xsd:int" />
    <xsd:attribute name="decimals" type="xsd:int" />
    <xsd:attribute name="radix" type="xsd:int" />
    <xsd:attribute name="nullable" type="xsd:boolean" />
    <xsd:attribute name="field" type="xsd:string" />
  </xsd:complexType>

  <xsd:simpleType name="tableType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TABLE" />
      <xsd:enumeration value="VIEW" />
      <xsd:enumeration value="SYSTEM TABLE" />
      <xsd:enumeration value="GLOBAL TEMPORARY" />
      <xsd:enumeration value="LOCAL TEMPORARY" />
      <xsd:enumeration value="ALIAS" />
      <xsd:enumeration value="SYNONYM" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="dataType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="array" />
      <xsd:enumeration value="bigint" />
      <xsd:enumeration value="binary" />
      <xsd:enumeration value="bit" />
      <xsd:enumeration value="blob" />
      <xsd:enumeration value="boolean" />
      <xsd:enumeration value="char" />
      <xsd:enumeration value="clob" />
      <xsd:enumeration value="datalink" />
      <xsd:enumeration value="date" />
      <xsd:enumeration value="decimal" />
      <xsd:enumeration value="distinct" />
      <xsd:enumeration value="double" />
      <xsd:enumeration value="float" />
      <xsd:enumeration value="integer" />
      <xsd:enumeration value="java_object" />
      <xsd:enumeration value="longnvarchar" />
      <xsd:enumeration value="longvarbinary" />
      <xsd:enumeration value="longvarchar" />
      <xsd:enumeration value="nchar" />
      <xsd:enumeration value="nclob" />
      <xsd:enumeration value="null" />
      <xsd:enumeration value="numeric" />
      <xsd:enumeration value="nvarchar" />
      <xsd:enumeration value="other" />
      <xsd:enumeration value="real" />
      <xsd:enumeration value="ref" />
      <xsd:enumeration value="rowid" />
      <xsd:enumeration value="smallint" />
      <xsd:enumeration value="sqlxml" />
      <xsd:enumeration value="struct" />
      <xsd:enumeration value="time" />
      <xsd:enumeration value="timestamp" />
      <xsd:enumeration value="tinyint" />
      <xsd:enumeration value="varbinary" />
      <xsd:enumeration value="varchar" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== hanneslehmann/as-db/src/test/resources/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://as.tibco.com/db.xsd">
  <table name="TABLE1" />
  <table name="TABLE2" schema="SCHEMA1">
    <column name="COLUMN1" type="varchar" size="255" keySequence="1" />
    <column name="COLUMN2" type="timestamp" keySequence="2" />
    <column name="COLUMN3" type="numeric" size="16" decimals="2" />
  </table>
  <table name="TABLE3" space="Space2" catalog="CATALOG1" schema="SCHEMA1">
    <selectSQL>SELECT * FROM TABLE3 WHERE COLUMN3 > 10</selectSQL>
    <countSQL>SELECT COUNT(*) FROM TABLE3 WHERE COLUMN3 > 10</countSQL>
    <insertSQL>INSERT INTO TABLE3 (COLUMN1, COLUMN2, COLUMN3) VALUES
        (?, ?, ?)</insertSQL>
    <column name="COLUMN1" field="Field1" />
    <column name="COLUMN2" field="Field2" />
    <column name="COLUMN3" field="Field3" />
  </table>
</database>

=== hanneslehmann/as-db/src/test/resources/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<database driver="org.h2.Driver" url="jdbc:h2:mem:test"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://as.tibco.com/db.xsd">
  <table name="MyTable" space="MySpace">
    <column name="column1" field="field1" type="numeric" size="12" />
    <column name="column2" field="field2" type="char" size="10" />
    <column name="column3" field="field3" />
    <column name="column4" field="field4" />
    <column name="column5" field="field5" />
    <column name="column6" field="field6" />
    <column name="column7" field="field7" />
    <column name="column8" field="field8" />
    <column name="column9" field="field9" />
    <column name="column10" field="field10" />
  </table>
</database>
